apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::804263606815:role/eksctl-eks-cluster-nodegroup-eks-NodeInstanceRole-MJ4YW4EZ6QC0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - integrations
      rolearn: arn:aws:iam::804263606815:role/ec2_ssm_role
      username: integrations
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::804263606815:user/dev
      username: dev
